general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim après 2min
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Clavier off après 2min
listener {
    timeout = 120
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Lock après 3min
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# Écran off après 4min (APRÈS le lock)
listener {
    timeout = 240
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend après 6min sur batterie
listener {
    timeout = 360
    on-timeout = bash -c '[ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && systemctl suspend'
}

# Hibernate après 1h sur batterie
listener {
    timeout = 3600
    on-timeout = bash -c '[ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && systemctl hibernate'
}