-- Generated by nwg-displays on 2026-05-29 at 14:58:47.
-- If nwg-displays regenerates monitors.conf, manually convert it here.

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1920x1080@60.0",
    position = "2471x1396",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60.0",
    position = "4391x1396",
    scale    = 1.0,
})
