-- Generated by nwg-displays on 2026-08-01 at 15:42:28. Do not edit manually.

hl.monitor({
    output = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006648",
    mode = "1920x1080@60.0",
    position = "4391x1396",
    scale = 1.0
})
hl.monitor({
    output = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661",
    mode = "1920x1080@60.0",
    position = "2471x1396",
    scale = 1.0
})
