-- Generated by nwg-displays on 2026-02-15 at 22:12:18.
-- If nwg-displays regenerates workspaces.conf, manually convert it here.

-- No gaps when only one window
hl.workspace_rule({
    workspace   = "w[1]",
    gaps_in     = 0,
    gaps_out    = 0,
    border_size = 0,
    no_rounding = true,
})

hl.workspace_rule({ workspace = "1",  monitor = "HDMI-A-2", default = true })
hl.workspace_rule({ workspace = "2",  monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "3",  monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "4",  monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "5",  monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "6",  monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "7",  monitor = "HDMI-A-1", default = true })
hl.workspace_rule({ workspace = "8",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "9",  monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-1" })
