-- Generated by nwg-displays on 2026-08-01 at 15:42:26. Do not edit manually.
-- (sauf la règle w[1] ci-dessous : ajoutée à la main, nwg-displays ne la
-- génère pas et l'écrase à chaque régénération — la remettre à chaque fois.)

-- No gaps when only one window
hl.workspace_rule({
    workspace   = "w[1]",
    gaps_in     = 0,
    gaps_out    = 0,
    border_size = 0,
    no_rounding = true,
})

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006661"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006648",
    default = true
})
hl.workspace_rule({
    workspace = "8",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006648"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006648"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "desc:Philips Consumer Electronics Company PHL 242V8 UHB2052006648"
})
